### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by neeta-1992** [amirsanni/Video-Call-App#33] opened 2020-01-16 16:07 UTC
Hello,
Thank you for this library But I am getting an issue when I try to run "php server.php" Then I am getting error of 
PHP Fatal error: Uncaught Error: Class 'GuzzleHttp\Psr7\Rfc7230' not found in C:\xampp\htdocs\video-call-app\ws\vendor\guzzlehttp\psr7\src\functions.php:792

Please help me to find out the issue.

**Comment by amirsanni** [comment] 2020-01-16 17:09
@neeta-1992 do `composer install`.

**Comment by neeta-1992** [comment] 2020-01-17 10:31
I have tried with composer install 2-3 time before and also tried just now but still getting same error.

**Comment by amirsanni** [comment] 2020-02-09 11:21
Try `composer dump-autoload`

**Comment by amirsanni** [comment] 2020-02-19 18:22
Hi, were you able to fix this issue?

**Comment by Naktibalda** [comment] 2020-03-27 17:43
@amirsanni This issue was raised in ##php channel on Freenode.

The problem is that you committed vendor dir to git, but Rfc7230.php file is missing in https://github.com/amirsanni/Video-Call-App/tree/master/ws/vendor/guzzlehttp/psr7/src

For comparison, here is what it should be: https://github.com/guzzle/psr7/blob/master/src/Rfc7230.php

I have no idea how it could happen, but committing vendor directory is a bad practice, the best solution would be to delete vendor directory and add it to .gitignore

**Comment by amirsanni** [comment] 2020-03-27 19:05
@Naktibalda Thanks. Just did that. Hopefully, there will be no such issue in the future. Thank you.

**Closed by amirsanni** 2020-03-27 19:05 UTC
